import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Devs Thought</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="h-[100vh] justify-center max-w-[400px] mx-auto rounded-2xl py-10 ">
          <div>
            <div className="bg-[#1B2730] max-w-[300px] mx-auto h-[100px]  rounded-lg ">
              {" "}
              Miki
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
